name: Docker

on:
  push:
    branches:
      - "master"

jobs:
  Docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc:
          - "8.10.4"
        debian:
          - buster
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{ github.repository_owner }}/haskell:${{ matrix.ghc }}-${{ matrix.debian }}"
          build-args: "GHC_VERSION=${{ matrix.ghc }},DEBIAN_TAG=${{ matrix.debian }}"
